export const ITEM_STATUSES = {
  ITEM_PENDING: 201,
  ITEM_COMPLETED: 202,
  ITEM_CANCELLED: 203,
  ITEM_PENDING_REVIEW: 204,
  ITEM_SHIPPED: 205,
}

export const SUPPLY_STATUSES = {
  SUPPLY_PENDING: 301,
  SUPPLY_ACCEPTED: 302,
  SUPPLY_REFUSED: 303,
  SUPPLY_MODIFIED: 304,
  SUPPLY_SELECTED: 305,
};
